# SPDX-FileCopyrightText: 2025 Deutsche Telekom AG and others
#
# SPDX-License-Identifier: CC0-1.0

arc:
  ai:
    clients:
      - id: GPT4o-mini
        modelName: gpt-4o-mini
        client: "openai"
        apiKey: ${OPENAI_API_KEY}
        url: https://api.openai.com/v1/
